serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@dataloop-infra.iam.gserviceaccount.com

webhook:
  create: true

certController:
  create: true

securityContext:
  fsGroup: 65534
  runAsUser: 65534
  runAsNonRoot: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Configure GCP Secret Manager as the default provider
secretStore:
  defaultStore: gcp-store

# GCP Secret Manager configuration
gcp:
  enabled: true
  projectID: dataloop-infra
  auth:
    secretRef:
      name: gcp-secret-store-creds
      key: credentials.json 