apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret-store
  namespace: argocd
spec:
  project: default
  source:
    chart: external-secret-store
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.5
    helm:
      valueFiles:
        - ../../values/external-secrets-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
