apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-store
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          name: gcp-secret-store-creds
          key: credentials.json
      projectID: dataloop-infra